# docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql-hitmatrix
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sw63828
      MYSQL_DATABASE: lotto_ai3_hitmatrix
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
